FROM python:3.9

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y build-essential

# Install Rasa
RUN pip install --upgrade pip
RUN pip install rasa==3.6.10 rasa-sdk==3.6.1 pandas openpyxl

# Copy your project files
COPY . .

# Expose port
EXPOSE 5005

# Run the Rasa server
CMD ["rasa", "run", "--enable-api", "--cors", "*", "--port", "5005"]
