FROM python:3.9

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy all files
COPY . .

# Expose Rasa port
EXPOSE 5005

# Default command
CMD ["rasa", "run", "--enable-api", "--port", "5005", "--cors", "*"]
